# -*- coding: utf-8 -*-
# ==========================================
# Mohamed Store - Enigma2 Plugin Extension
# Auto-generated by Mohamed Store Plugin Tool
# Python 2 & Python 3 fully compatible
# ==========================================

from Plugins.Plugin import PluginDescriptor
from Screens.Screen import Screen
from Screens.MessageBox import MessageBox
from Components.MenuList import MenuList
from Components.Label import Label
from Components.ActionMap import ActionMap
from Components.Console import Console
import json
import os
import sys

# Try importing standby and main loop controllers
try:
    from Screens.Standby import TryQuitMainloop
except ImportError:
    TryQuitMainloop = None

try:
    import enigma
except ImportError:
    enigma = None

# Core configuration variables
VERSION_URL = "https://raw.githubusercontent.com/wwwgoper77-wq/MohamedStore/main/version.json"
STORE_URL = "https://raw.githubusercontent.com/wwwgoper77-wq/MohamedStore/main/feed/index.json"
PLUGIN_VERSION = "1.0"

def load_json(url):
    try:
        if sys.version_info >= (3, 0):
            import urllib.request as urllib2
        else:
            import urllib2
        
        req = urllib2.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        response = urllib2.urlopen(req, timeout=12)
        data = response.read()
        if isinstance(data, bytes):
            data = data.decode('utf-8')
        return json.loads(data)
    except Exception as e:
        print("[MohamedStore] load_json error: " + str(e))
        return None

class MohamedStore(Screen):
    skin = """
<screen name="MohamedStore" position="center,center" size="1280,720" title="Mohamed Store">
    <eLabel position="0,0" size="1280,80" backgroundColor="#1a1a1a" zPosition="-1" />
    
    <widget name="categories_list" position="40,110" size="280,480" itemHeight="50" scrollbarMode="showOnDemand" foregroundColor="#ffffff" backgroundColor="#202020" selectionFontColor="#ffffff" font="Regular;22" />
    
    <widget name="items_list" position="340,110" size="450,480" itemHeight="55" scrollbarMode="showOnDemand" foregroundColor="#ffffff" backgroundColor="#1a1a1a" selectionFontColor="#000000" font="Regular;22" />
    
    <eLabel position="810,110" size="430,480" backgroundColor="#252525" zPosition="-1" />
    <widget name="description" position="830,140" size="390,420" font="Regular;22" foregroundColor="#dddddd" backgroundColor="#252525" transparent="1" valign="top" />
    
    <eLabel position="0,620" size="1280,2" backgroundColor="#333333" />
    <widget name="key_red" position="90,648" size="150,35" font="Regular;22" foregroundColor="#ffffff" backgroundColor="#1a1a1a" transparent="1" halign="left" />
    <widget name="key_green" position="310,648" size="150,35" font="Regular;22" foregroundColor="#ffffff" backgroundColor="#1a1a1a" transparent="1" halign="left" />
</screen>
"""

    def __init__(self, session):
        Screen.__init__(self, session)
        self["categories_list"] = MenuList([])
        self["items_list"] = MenuList([])
        self["description"] = Label("Checking for updates...")
        self["key_red"] = Label("Exit")
        self["key_green"] = Label("Install")
        
        self.store_data = {}
        self.categories = []
        self.current_items = []
        self.active_focus = "categories"
        self.my_console = Console()
        
        self["actions"] = ActionMap(["OkCancelActions", "DirectionActions", "ColorActions"], {
            "cancel": self.close,
            "red": self.close,
            "green": self.download,
            "ok": self.press_ok,
            "up": self.go_up,
            "down": self.go_down,
            "left": self.switch_to_categories,
            "right": self.switch_to_items,
        }, -1)
        
        self["categories_list"].onSelectionChanged.append(self.category_changed)
        self["items_list"].onSelectionChanged.append(self.item_changed)
        
        self.onLayoutFinish.append(self.check_for_updates)

    def is_newer_version(self, online, current):
        try:
            online_parts = [int(x) for x in online.split('.')]
            current_parts = [int(x) for x in current.split('.')]
            max_len = max(len(online_parts), len(current_parts))
            online_parts += [0] * (max_len - len(online_parts))
            current_parts += [0] * (max_len - len(current_parts))
            return online_parts > current_parts
        except Exception as e:
            print("[MohamedStore] Version Check Parsing Error: " + str(e))
            try:
                return float(online) > float(current)
            except:
                return online != current

    def check_for_updates(self):
        try:
            ver_data = load_json(VERSION_URL)
            if ver_data and "plugin_version" in ver_data:
                online_version = str(ver_data["plugin_version"])
                if self.is_newer_version(online_version, PLUGIN_VERSION):
                    self.session.openWithCallback(
                        self.updateAnswer,
                        MessageBox,
                        "A new version of Mohamed Store is available.\\nDo you want to update now?",
                        MessageBox.TYPE_YESNO
                    )
                    return
        except Exception as e:
            print("[MohamedStore] Update Check Exception: " + str(e))
            
        self.load_store()

    def updateAnswer(self, answer):
        if answer:
            self["description"].setText("Downloading and installing self-update...\\nPlease wait...")
            update_url = "https://raw.githubusercontent.com/wwwgoper77-wq/MohamedStore/main/MohamedStore/plugin.py"
            dest_path = "/usr/lib/enigma2/python/Plugins/Extensions/MohamedStore/plugin.py"
            temp_path = "/tmp/plugin.py"
            
            # Robust, secure update command:
            # 1. Clean up stale local temporary downloaded files first
            # 2. Download code using wget with SSL fallback to curl -k -L for maximum compatibility
            # 3. Ensure the downloaded file is not empty and contains valid plugin structures
            # 4. Safely move the verified script to replace the active plugin
            # 5. Erase bytecode caches (.pyc, .pyo, and __pycache__) to force clean python recompilation
            cmd = (
                "rm -f {temp_path} && "
                "(wget --no-check-certificate -O {temp_path} '{update_url}' || curl -k -L -o {temp_path} '{update_url}') && "
                "[ -s {temp_path} ] && grep -q 'class MohamedStore' {temp_path} && "
                "mv -f {temp_path} {dest_path} && "
                "rm -f {dest_path}c {dest_path}o && "
                "rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MohamedStore/__pycache__"
            ).format(temp_path=temp_path, update_url=update_url, dest_path=dest_path)
            
            self.my_console.ePopen(cmd + " 2>&1", self.update_finished)
        else:
            self.load_store()

    def update_finished(self, result, retval, extra_args=None):
        if retval == 0:
            self.session.openWithCallback(
                self.restartGUICallback,
                MessageBox,
                "Mohamed Store updated successfully!\\n\\nRestart GUI now?",
                MessageBox.TYPE_YESNO
            )
        else:
            error = result.strip() if result else "Unknown network or file validation error"
            print("[MohamedStore] Self-Update Failed: " + str(error))
            self["description"].setText(
                "Self-Update Failed!\\n\\nExit Code: " + str(retval) + "\\n\\n" + str(error)
            )

    def restartGUICallback(self, answer):
        if answer:
            try:
                if TryQuitMainloop:
                    self.session.open(TryQuitMainloop, 3)
                else:
                    enigma.quitMainloop(3)
            except:
                try:
                    enigma.quitMainloop(3)
                except:
                    try:
                        enigma.eApp.getInstance().quit(3)
                    except:
                        pass
        else:
            self.load_store()

    def load_store(self):
        try:
            data = load_json(STORE_URL)
            if not data or "categories" not in data:
                self["description"].setText("Failed to load store data from GitHub.")
                return
            
            store_title = "%s v%s" % (data.get("store_name", "M Store"), data.get("version", "1.0"))
            self.setTitle(store_title)
            
            self.store_data = data["categories"]
            self.categories = list(self.store_data.keys())
            
            if self.categories:
                display_cats = [str(cat).replace("_", " ").capitalize() for cat in self.categories]
                self["categories_list"].setList(display_cats)
                self.category_changed()
            else:
                self["description"].setText("Store is empty.")
        except Exception as e:
            self["description"].setText("Load Store Error: " + str(e))

    def category_changed(self):
        try:
            if self.active_focus != "categories" and len(self.categories) == 0:
                return
            idx = self["categories_list"].getSelectionIndex()
            if idx < 0 or idx >= len(self.categories):
                return
            
            selected_cat = self.categories[idx]
            self.current_items = self.store_data.get(selected_cat, [])
            
            if self.current_items and isinstance(self.current_items, list):
                list_names = ["%s  (v%s)" % (str(item.get("name", "Unknown")), str(item.get("version", "1.0"))) for item in self.current_items]
                self["items_list"].setList(list_names)
                self.item_changed()
            else:
                self["items_list"].setList([])
                self["description"].setText("No items found in this section.")
        except Exception as e:
            self["description"].setText("Category Change Error: " + str(e))

    def item_changed(self):
        try:
            idx = self["items_list"].getSelectionIndex()
            if idx < 0 or idx >= len(self.current_items) or not self.current_items:
                return
            
            item = self.current_items[idx]
            cat_idx = self["categories_list"].getSelectionIndex()
            cat_name = str(self.categories[cat_idx]).replace("_", " ").capitalize() if cat_idx >= 0 else "Unknown"
            
            info_text = "Section: %s\\n\\nName: %s\\nVersion: %s\\n\\nDescription:\\n%s" % (
                cat_name,
                str(item.get("name", "")),
                str(item.get("version", "")),
                str(item.get("description", "No description available."))
            )
            self["description"].setText(info_text)
        except Exception as e:
            self["description"].setText("Item Change Error: " + str(e))

    def switch_to_items(self):
        if self.current_items:
            self.active_focus = "items"
            self["description"].setText("Navigating: Items List\\n\\nPress OK or Green to Install.")

    def switch_to_categories(self):
        self.active_focus = "categories"
        self.category_changed()

    def go_up(self):
        try:
            if self.active_focus == "categories":
                self["categories_list"].up()
            else:
                self["items_list"].up()
        except:
            pass

    def go_down(self):
        try:
            if self.active_focus == "categories":
                self["categories_list"].down()
            else:
                self["items_list"].down()
        except:
            pass

    def press_ok(self):
        if self.active_focus == "categories":
            self.switch_to_items()
        else:
            self.download()

    def download(self):
        try:
            idx = self["items_list"].getSelectionIndex()
            if idx >= 0 and idx < len(self.current_items) and self.current_items:
                item = self.current_items[idx]
                url = item.get("file", "").strip()
                if not url:
                    self["description"].setText("Error: Download URL is missing in JSON.")
                    return
                
                self["description"].setText("Downloading and installing %s...\\nPlease wait..." % str(item.get("name", "")))
                
                if url.endswith(".deb"):
                    cmd = "wget --no-check-certificate -O /tmp/addon.deb '%s' && dpkg -i /tmp/addon.deb && rm -f /tmp/addon.deb" % url
                else:
                    cmd = "wget --no-check-certificate -O /tmp/addon.ipk '%s' && opkg install --force-overwrite /tmp/addon.ipk && rm -f /tmp/addon.ipk" % url
                    
                self.my_console.ePopen(cmd + " 2>&1", self.download_finished)
        except Exception as e:
            print("[MohamedStore] Download Error: " + str(e))
            self["description"].setText("Execution error, check system log.")

    def download_finished(self, result, retval, extra_args=None):
        if retval == 0:
            self.session.openWithCallback(self.restartCallback, MessageBox, "Installation completed successfully!\\n\\nRestart GUI now?", MessageBox.TYPE_YESNO)
        else:
            error = result.strip() if result else "Unknown error"
            print("[MohamedStore] Install output:\\n" + str(error))
            self["description"].setText(
                "Installation Failed!\\n\\nExit Code: " + str(retval) + "\\n\\n" + str(error)
            )

    def restartCallback(self, answer):
        if answer:
            try:
                if TryQuitMainloop:
                    self.session.open(TryQuitMainloop, 3)
                else:
                    enigma.quitMainloop(3)
            except:
                try:
                    enigma.quitMainloop(3)
                except:
                    try:
                        enigma.eApp.getInstance().quit(3)
                    except:
                        pass
        else:
            self["description"].setText("Installation completed successfully. Restart skipped.")

# Descriptor hooks for Enigma2
def main(session, **kwargs):
    session.open(MohamedStore)

def Plugins(**kwargs):
    return PluginDescriptor(
        name="Mohamed Store",
        description="Download and install addons, plugins, and softcams",
        where=PluginDescriptor.WHERE_PLUGINMENU,
        icon="plugin.png",
        fnc=main
    )